// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/service.proto

package filedownloadmanager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownloadType int32

const (
	DownloadType_SYNC  DownloadType = 0
	DownloadType_ASYNC DownloadType = 1
)

var DownloadType_name = map[int32]string{
	0: "SYNC",
	1: "ASYNC",
}

var DownloadType_value = map[string]int32{
	"SYNC":  0,
	"ASYNC": 1,
}

func (x DownloadType) String() string {
	return proto.EnumName(DownloadType_name, int32(x))
}

func (DownloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{0}
}

type SampleRequest struct {
	Field_1              string   `protobuf:"bytes,1,opt,name=field_1,json=field1,proto3" json:"field_1,omitempty"`
	Field_2              string   `protobuf:"bytes,2,opt,name=field_2,json=field2,proto3" json:"field_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleRequest) Reset()         { *m = SampleRequest{} }
func (m *SampleRequest) String() string { return proto.CompactTextString(m) }
func (*SampleRequest) ProtoMessage()    {}
func (*SampleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{0}
}

func (m *SampleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleRequest.Unmarshal(m, b)
}
func (m *SampleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleRequest.Marshal(b, m, deterministic)
}
func (m *SampleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleRequest.Merge(m, src)
}
func (m *SampleRequest) XXX_Size() int {
	return xxx_messageInfo_SampleRequest.Size(m)
}
func (m *SampleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SampleRequest proto.InternalMessageInfo

func (m *SampleRequest) GetField_1() string {
	if m != nil {
		return m.Field_1
	}
	return ""
}

func (m *SampleRequest) GetField_2() string {
	if m != nil {
		return m.Field_2
	}
	return ""
}

type SampleResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleResponse) Reset()         { *m = SampleResponse{} }
func (m *SampleResponse) String() string { return proto.CompactTextString(m) }
func (*SampleResponse) ProtoMessage()    {}
func (*SampleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{1}
}

func (m *SampleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleResponse.Unmarshal(m, b)
}
func (m *SampleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleResponse.Marshal(b, m, deterministic)
}
func (m *SampleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleResponse.Merge(m, src)
}
func (m *SampleResponse) XXX_Size() int {
	return xxx_messageInfo_SampleResponse.Size(m)
}
func (m *SampleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SampleResponse proto.InternalMessageInfo

func (m *SampleResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *SampleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{2}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AddUserResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SecretKey            string   `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{3}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *AddUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserResponse) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type DownloadRequest struct {
	Files                []string     `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	DownloadType         DownloadType `protobuf:"varint,2,opt,name=download_type,json=downloadType,proto3,enum=payoutlinks.DownloadType" json:"download_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{4}
}

func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(m, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *DownloadRequest) GetDownloadType() DownloadType {
	if m != nil {
		return m.DownloadType
	}
	return DownloadType_SYNC
}

type DownloadResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Files                []string `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadResponse) Reset()         { *m = DownloadResponse{} }
func (m *DownloadResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadResponse) ProtoMessage()    {}
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{5}
}

func (m *DownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResponse.Unmarshal(m, b)
}
func (m *DownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResponse.Marshal(b, m, deterministic)
}
func (m *DownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResponse.Merge(m, src)
}
func (m *DownloadResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadResponse.Size(m)
}
func (m *DownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResponse proto.InternalMessageInfo

func (m *DownloadResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DownloadResponse) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterEnum("payoutlinks.DownloadType", DownloadType_name, DownloadType_value)
	proto.RegisterType((*SampleRequest)(nil), "payoutlinks.SampleRequest")
	proto.RegisterType((*SampleResponse)(nil), "payoutlinks.SampleResponse")
	proto.RegisterType((*AddUserRequest)(nil), "payoutlinks.AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "payoutlinks.AddUserResponse")
	proto.RegisterType((*DownloadRequest)(nil), "payoutlinks.DownloadRequest")
	proto.RegisterType((*DownloadResponse)(nil), "payoutlinks.DownloadResponse")
}

func init() {
	proto.RegisterFile("rpc/service.proto", fileDescriptor_ec64d44e618a02a6)
}

var fileDescriptor_ec64d44e618a02a6 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0xce, 0xd2, 0x40,
	0x14, 0xc5, 0x6d, 0xfd, 0x80, 0xf6, 0xfa, 0x51, 0x70, 0xc0, 0x58, 0x2b, 0x24, 0xa6, 0x6e, 0x8c,
	0x0b, 0x0c, 0x75, 0xe3, 0xca, 0xa4, 0x48, 0x34, 0xc6, 0xe8, 0xa2, 0xe8, 0x42, 0x37, 0xcd, 0xd8,
	0xb9, 0x90, 0x09, 0xfd, 0x67, 0xa7, 0xd5, 0xf4, 0x89, 0x7d, 0x0d, 0x43, 0x3b, 0x03, 0xad, 0xc1,
	0xc4, 0x1d, 0x67, 0xce, 0xe4, 0x77, 0xce, 0xdc, 0x4b, 0xe1, 0x7e, 0x91, 0x47, 0x2f, 0x04, 0x16,
	0x3f, 0x79, 0x84, 0xab, 0xbc, 0xc8, 0xca, 0x8c, 0xdc, 0xcb, 0x69, 0x9d, 0x55, 0x65, 0xcc, 0xd3,
	0xa3, 0x70, 0x7d, 0x18, 0xef, 0x68, 0x92, 0xc7, 0x18, 0xe0, 0x8f, 0x0a, 0x45, 0x49, 0x1e, 0xc2,
	0x68, 0xcf, 0x31, 0x66, 0xe1, 0xda, 0xd6, 0x9e, 0x68, 0xcf, 0xcc, 0x60, 0xd8, 0xc8, 0xf5, 0xc5,
	0xf0, 0x6c, 0xbd, 0x63, 0x78, 0xee, 0x7b, 0xb0, 0x14, 0x42, 0xe4, 0x59, 0x2a, 0x90, 0x2c, 0x01,
	0xb8, 0x08, 0x45, 0x15, 0x45, 0x28, 0x44, 0x83, 0x31, 0x02, 0x93, 0x8b, 0x5d, 0x7b, 0x40, 0x6c,
	0x18, 0x25, 0x28, 0x04, 0x3d, 0xa0, 0x24, 0x29, 0xe9, 0x6e, 0xc0, 0xf2, 0x19, 0xfb, 0x22, 0xb0,
	0x50, 0x75, 0x1c, 0x30, 0x2a, 0x81, 0x45, 0x4a, 0x13, 0x94, 0x7d, 0xce, 0x9a, 0xcc, 0x61, 0x80,
	0x09, 0xe5, 0xb1, 0xa4, 0xb4, 0xc2, 0x3d, 0xc2, 0xe4, 0xcc, 0xf8, 0xbf, 0x3e, 0xdd, 0x0c, 0xfd,
	0xaf, 0x8c, 0x25, 0x80, 0xc0, 0xa8, 0xc0, 0x32, 0x3c, 0x62, 0x6d, 0xdf, 0x34, 0xae, 0xd9, 0x9e,
	0x7c, 0xc0, 0xda, 0x3d, 0xc0, 0x64, 0x9b, 0xfd, 0x4a, 0xe3, 0x8c, 0x32, 0xd5, 0x78, 0x0e, 0x83,
	0x3d, 0x8f, 0xf1, 0x94, 0x73, 0xf7, 0xd4, 0xaa, 0x11, 0xe4, 0x35, 0x8c, 0x99, 0xbc, 0x18, 0x96,
	0x75, 0xde, 0x06, 0x59, 0xde, 0xa3, 0x55, 0x67, 0x19, 0x2b, 0x85, 0xfa, 0x5c, 0xe7, 0x18, 0xdc,
	0xb2, 0x8e, 0x72, 0x5f, 0xc1, 0xf4, 0x12, 0x24, 0x9f, 0x65, 0x81, 0xce, 0x99, 0x9c, 0x8a, 0xce,
	0xd9, 0x25, 0x59, 0xef, 0x24, 0x3f, 0x7f, 0x0a, 0xb7, 0x5d, 0x2e, 0x31, 0xe0, 0x66, 0xf7, 0xf5,
	0xd3, 0x9b, 0xe9, 0x1d, 0x62, 0xc2, 0xc0, 0x6f, 0x7e, 0x6a, 0xde, 0x6f, 0x0d, 0x66, 0x6f, 0x79,
	0x8c, 0xea, 0xe6, 0x47, 0x9a, 0xd2, 0x03, 0x16, 0xc4, 0x87, 0x61, 0xbb, 0x5b, 0xe2, 0xf4, 0x9a,
	0xf6, 0xfe, 0x33, 0xce, 0xe3, 0xab, 0x9e, 0x6c, 0xb9, 0x85, 0x91, 0xdc, 0x07, 0xe9, 0xdf, 0xeb,
	0x6f, 0xda, 0x59, 0x5c, 0x37, 0x25, 0xe5, 0x1d, 0x18, 0xaa, 0x1b, 0x59, 0x5c, 0x1d, 0x9a, 0xe2,
	0x2c, 0xff, 0xe1, 0xb6, 0xa0, 0xcd, 0x83, 0x6f, 0xb3, 0xd3, 0x5c, 0xd4, 0x70, 0x93, 0xf6, 0xa1,
	0xdf, 0x87, 0xcd, 0xb7, 0xf1, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x35, 0x10, 0x36,
	0x30, 0x03, 0x00, 0x00,
}
